### ISSUE TITLE
TypeError: Cannot read property '_tiles' of undefined

### ISSUE THREAD

**Issue by Algunenano** [CartoDB/torque#306]
```
[2019-05-29 09:12:14.886] [FATAL] [default] - TypeError: Cannot read property '_tiles' of undefined
    at PointRenderer.setCartoCSS (/home/ubuntu/www/node-windshaft/releases/20190521103931/node_modules/torque.js/lib/torque/renderer/point.js:122:57)
    at new PointRenderer (/home/ubuntu/www/node-windshaft/releases/20190521103931/node_modules/torque.js/lib/torque/renderer/point.js:77:10)
    at /home/ubuntu/www/node-windshaft/releases/20190521103931/node_modules/windshaft/lib/windshaft/renderers/torque/png_renderer.js:90:29
    at /home/ubuntu/www/node-windshaft/releases/20190521103931/node_modules/windshaft/lib/windshaft/renderers/torque/renderer.js:173:17
    at ctor.PSQLAdaptor.ctor._handleResult (/home/ubuntu/www/node-windshaft/releases/20190521103931/node_modules/windshaft/lib/windshaft/renderers/torque/psq
l_adaptor.js:16:9)
    at Result.<anonymous> (/home/ubuntu/www/node-windshaft/releases/20190521103931/node_modules/cartodb-psql/lib/psql.js:325:24)
    at Result.Query.handleReadyForQuery (/home/ubuntu/www/node-windshaft/releases/20190521103931/node_modules/pg/lib/query.js:144:10)
    at Connection.<anonymous> (/home/ubuntu/www/node-windshaft/releases/20190521103931/node_modules/pg/lib/client.js:184:19)
    at Connection.emit (events.js:189:13)
    at Socket.<anonymous> (/home/ubuntu/www/node-windshaft/releases/20190521103931/node_modules/pg/lib/connection.js:135:12)
TypeError: Cannot read property '_tiles' of undefined
    at PointRenderer.setCartoCSS (/home/ubuntu/www/node-windshaft/releases/20190521103931/node_modules/torque.js/lib/torque/renderer/point.js:122:57)
    at new PointRenderer (/home/ubuntu/www/node-windshaft/releases/20190521103931/node_modules/torque.js/lib/torque/renderer/point.js:77:10)
    at /home/ubuntu/www/node-windshaft/releases/20190521103931/node_modules/windshaft/lib/windshaft/renderers/torque/png_renderer.js:90:29
    at /home/ubuntu/www/node-windshaft/releases/20190521103931/node_modules/windshaft/lib/windshaft/renderers/torque/renderer.js:173:17
    at ctor.PSQLAdaptor.ctor._handleResult (/home/ubuntu/www/node-windshaft/releases/20190521103931/node_modules/windshaft/lib/windshaft/renderers/torque/psql_adaptor.js:16:9)
    at Result.<anonymous> (/home/ubuntu/www/node-windshaft/releases/20190521103931/node_modules/cartodb-psql/lib/psql.js:325:24)
    at Result.Query.handleReadyForQuery (/home/ubuntu/www/node-windshaft/releases/20190521103931/node_modules/pg/lib/query.js:144:10)
    at Connection.<anonymous> (/home/ubuntu/www/node-windshaft/releases/20190521103931/node_modules/pg/lib/client.js:184:19)
    at Connection.emit (events.js:189:13)
    at Socket.<anonymous> (/home/ubuntu/www/node-windshaft/releases/20190521103931/node_modules/pg/lib/connection.js:135:12)
[2019-05-29 09:12:14.887] [INFO] [default] - Process is going to exit with code: 1
```

As with https://github.com/CartoDB/turbo-carto/issues/83, it's crashing in production.

cc/ @CartoDB/rt-managers

**Comment by Algunenano** [comment]
3 instances of this error so far today.

**Comment by jgoizueta** [comment]
It seems that undefined layer in a torque renderer has caused problems before and [has been handled by coping with undefined layers](https://github.com/CartoDB/torque/commit/e784dcb048aec42b616117393d7b43b02e8d0d6c#diff-4fd2c26bc2bdab1bd41893c70cbb08de). I'm not sure that's the best option, but I'm not sure either if it's worth investigating the cause of the undefined layer.

**Comment by rafatower** [comment]
I managed to reproduce the issue with a point dataset and the following cartocss:

```css
Map {
  -torque-frame-count: 1;
  -torque-animation-duration: 30;
  -torque-time-attribute: "cartodb_id";
  -torque-aggregation-function: "count(1)";
  -torque-resolution: 4;
  -torque-data-aggregation: linear;
}
#layer {
  marker-width: 16.6;
  /*marker-width: ramp([temp], range(2, 40), jenks(6));*/
  marker-fill-opacity: 1;
  marker-file: url(http://cartodb-libs.global.ssl.fastly.net/cartodbui/assets/unversioned/images/alphamarker.png);
  marker-allow-overlap: true;
  marker-line-width: 1;
  marker-line-color: #FFFFFF;
  marker-line-opacity: 1;
  marker-comp-op: darken;
  image-filters: colorize-alpha(#4b2991,#872ca2,#c0369d,#ea4f88,#fa7876,#f6a97a,#edd9a3);
}
```

and then trying to `Export image...` from Builder.

That said, there are a few dark corners in this very specific use case:
- Torque + Turbo-Carto is a half supported feature at best, and officially not supported. See https://github.com/CartoDB/cartodb/issues/10947 (it's a long discussion with branches, but very relevant).
- Mind the commented out code: part of the work is done client-side (receiving the torque json info and rendering static or animated stuff in the browser), whereas another part is done by the tiler (see 

https://github.com/CartoDB/Windshaft/blob/a9b3b6492c4e01b16b12c807bf10f6d5d2661d32/lib/windshaft/renderers/torque/png_renderer.js#L90

in the stack trace). Usually that works by "compiling" turbo-carto to plain cartocss and then handing it over to the tiler, but the commented out code messes it up as it believes it has a turbo-carto, here: 

https://github.com/CartoDB/torque/blob/4d2540ef98018775cfcd8fee8df2c39c6fc13230/lib/torque/renderer/point.js#L121

and that does NOT happen when that code is uncommented.

So, I suspect the crash is triggered by some legacy "dead code" that is only reachable in this faulty condition: commented code that resembles turbo-carto.
